[package]
name = "type-key"
description = "Unique type identifier for any non-static type"
version = "1.0.0"
edition = "2021"
authors = ["storycraft <storycraft@pancake.sh>"]
license = "MIT"

[dependencies]
